[tools]
clojure = "1.12.6.1673"
java = "25"
mkcert = "1.4.4"

[tasks.services]
run = "docker compose up --build --detach"

[tasks.lint]
run = "clojure -M:dev -m clj-kondo.main --lint src test"

[tasks.gen-certs]
run = [
  "mkcert -key-file dev/certs/server.key -cert-file dev/certs/server.crt localhost",
  "openssl x509 -inform PEM -outform DER -in \"$(mkcert -CAROOT)/rootCA.pem\" | keytool -noprompt -import -alias myserver -keystore dev/jks/dev.jks -storepass muutos",
]

[tasks.test]
run = "clojure -J-Dapi.version=1.44 -J-Dclojure.main.report=stderr -X:dev kaocha.runner/exec-fn :seed 1272498040 :reporter kaocha.report/documentation"

[tasks.xr]
run = "clojure -J-Dapi.version=1.44 -J-Dclojure.main.report=stderr -X:dev user/check!"

[tasks.pgbench-init]
run = [
  "env PGPASSWORD=postgres pgbench --initialize --scale=10 --host=localhost --port=5432 --username=postgres --dbname=postgres",
  "env PGPASSWORD=postgres pgbench --initialize --scale=10 --host=localhost --port=5433 --username=postgres --dbname=postgres",
]

[tasks.pgbench-run]
run = "env PGPASSWORD=postgres pgbench --client=10 --jobs=2 --time=5 --host=localhost --port=5432 --username=postgres --dbname=postgres"

[tasks.pgbench]
depends = ["pgbench-init", "pgbench-run"]

[tasks.pagila]
run = [
  "curl -sL https://raw.githubusercontent.com/devrimgunduz/pagila//23f7fe7a1e9f5772f85fc14f530583ffa258c6d2/pagila-schema.sql -o dev/sql/1-pagila-schema.sql",
  "curl -sL https://raw.githubusercontent.com/devrimgunduz/pagila//23f7fe7a1e9f5772f85fc14f530583ffa258c6d2/pagila-schema-jsonb.sql -o dev/sql/2-pagila-schema-jsonb.sql",
  "curl -sL https://raw.githubusercontent.com/devrimgunduz/pagila//23f7fe7a1e9f5772f85fc14f530583ffa258c6d2/pagila-data.sql -o dev/sql/3-pagila-data.sql",
]

[tasks.recvlogical]
run = "pg_recvlogical -d postgres --slot my_slot --start --option=proto_version=2 --option=publication_names=p --host=localhost --port=5432 --username=postgres --password --file=-"
