# https://chaos-mesh.org/docs/simulate-heavy-stress-on-kubernetes/
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      'app': 'app'
  stressors:
    memory:
      workers: 3
      size: '32MB'
