name: Tests

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - uses: jdx/mise-action@v4
        with:
          version: 2025.3.11
          install: true
          cache: true

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            .cpcache
          key: deps-${{ hashFiles('deps.edn') }}
          restore-keys: deps-

      - name: Lint codebase
        run: clojure -M:dev -m clj-kondo.main --lint src test

      - name: Generate and import certificates
        run: mise gen-certs

      - name: Set SSL key and certificate file permissions
        run: |
          sudo chown 999:999 dev/certs/server.key
          sudo chmod 600 dev/certs/server.key
          sudo chmod 644 dev/certs/server.crt

      - name: Start services
        run: mise services

      - name: Run tests
        run: mise test

      - name: Stop services
        if: always()
        run: docker compose down --volumes --remove-orphans

      - name: Print logs
        if: always()
        run: docker compose logs

  transcribe:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - uses: jdx/mise-action@v4
        with:
          version: 2025.3.11
          install: true
          cache: true

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            .cpcache
          key: deps-${{ hashFiles('deps.edn') }}
          restore-keys: deps-

      - name: Generate and import certificates
        run: mise gen-certs

      - name: Set SSL key and certificate file permissions
        run: |
          sudo chown 999:999 dev/certs/server.key
          sudo chmod 600 dev/certs/server.key
          sudo chmod 644 dev/certs/server.crt

      - run: mise pagila

      - name: Start services
        run: mise services

      - name: Run transcriptions
        run: mise xr

      - name: Stop services
        if: always()
        run: docker compose down --volumes --remove-orphans

      - name: Print logs
        if: always()
        run: docker compose logs
